### PR TITLE
Remove references to rinkeby

### PR DESCRIPTION
**Pull request by alexanderattar**
- Remove all references to Rinkeby

### CODE REVIEW

**Review by ACC01ADE — COMMENTED** [review]
Canonically we always leave network details in our package. We just mark active as false. Additionally I have a new commit coming up that introduced a new Network variable `depreciated`. Where I mark these networks as depreciated and no longer interact-able.

**Review by ACC01ADE — CHANGES_REQUESTED** [review]
Instead of removing the objects from `src/networks.ts` set `active` to `false`. This allows to keep objects in place but block the ability to use/access them in our implementations. Additionally you can add a `depreciated?: boolean` to the `Network` interface in `tpes.ts` to further identify a network as no longer valid.
I would like to keep these networks in the file for tracking purposes of all assigned Holograph Chain IDs.

**Review by ACC01ADE — APPROVED** [review]

**Comment by ACC01ADE** [comment]
Pushed some commits that uses the approach of setting `active` to `false` and implementing the use of `depreciated` variable.

**Review by sogoiii — APPROVED** [review]
LGTM. @alexanderattar we should bump the version after this is merged and push it up to npm.

**Review by sogoiii — APPROVED** [review]
Lgtm

**Pull request merged**
